     XO         XO          OX         O X      O
 XXOX        XO          O          O           O
          OO         XO         XOO        XXXX X
      X OX       XXO          O          O      O
X       XXOX        OOOO        OX         X    O
      O          OXX        OX         O X      O
   OOOO          O        XXOOXX      XX X      O
O          XOOO        O         XXX          X O
        O         XO       X  O        XXO      O
OX          X         XO          OX         O  O
     XOOOO        OX X       XX                 O
    XOOOO       OX X       X  X                 O
 XX        XOOX       OOXXX        O          OOO
O           OXX       X O        X XO          OO
     O         XO          OXX        O X       O
     O          O     XXXX O          O         O
      OXXX        OO         XO        XXOO     O
 XXO XX      OOOO        X OX         OX        O
   O          OXXX       O  X       O           O
         O          OXX        OXX        O     O
XX       XOO          O         XOO         XXO O
  X O       X  O         XOX         O          O
       XOXX        O   X      O          O      O
     OOOO       X XO         XOX         XX     O
O X         OOX         O  X      XXO X        OO
 XX O        XOOOO      X OX         XOX        O
    XXXO        OOOO       X OX         XOX     O
X X        XOOOO        OX        X OX       X OO
        OX       X OXX        O          O      O
   OX          OXX X       OO X        O        O
         O          O        X O X      X OX    O
         O        XXO         XO          OX    O
 X O       XX O          O         XO           O
 X O         XO X        OX         O           O
  XX       O X         OOX         OX          OO
     XXO        OOOOX        OXX        X       O
O                    X O        X O        X OX O
        XO          OX         OX         O X   O
           O        XXO          OX         OX  O
   XXOOOX       OOX       XOXO        OX X      O
          O          OX         OX         OXX  O
OX         X X         OX         O          O  O
    O X        XOO         XOX         XO       O
     O          O        XXOX         OX        O
O            X         OXX        O   X      O  O
        XO X       XOOX        X O           O  O
      XO         XOX         O          OX      O
        X X       XOOOO        XOX         OX   O
 X   O        XXO          OX         O         O
     XO         XO          OXX        O        O
      O X         OXX         OOX        XO     O
    X O          OX         O XX       O        O
    X OX         OX X       O          O        O
OX       OOOX         XOX         X             O
       OO      XXX O        X OO         XXO    O
OO       XOO          O        XXOX        XX   O
   XO          O          O        XXO        X O
 X           X           XX         OOOO        O
       XO       XXOOOO        X           X     O
      X  X        X X        OOOO         O X   O
    O          O         XO         XOXX        O
X X X        XOOOO        OX         OX         O
     X OO        XXO X      X OO         X O    O
  X            X XX       OOOO         OX       O
 X         OOXXX       O   X       O   X      OOO
  XO        X O          OX         OX          O
       O     X    O       X XO         XO       O
 OXXX       XOO          OX         OOX         O
       XO          O X        O XX       O      O
       OX         OXXX       O          O       O
        O          OXXX       O   X      O      O
     XX        OOX         OX         OX        X
OX         X X         O          O          OX O
           OX         OX         OX         O X O
                     XX           XX       OOOO O
 XOXX        OX         O                      OO
         O         XO X        OX         O X   O
XX         OOXX       XO X         O          OOO
XXX        XO                      O          O X
      O XX        O X         OO XX       O     O
   OO          OX         XOX        XXO        O
     O          OX         OX X       OX        O
    X   OO       XXXO         XOO         X O   O
 XO         OOOO       XXX           X          O
       X OXXO       XOOO         O          XX  O
         O          OX         OXX        O X   O
         O           O           OXX        XOX O
           O       X XOX        XO          O   O
 OXX         OXX         OOX         O          O
        O  X        O XX        OOX         O X O
   X  O        XXO          O          O X      O
  XXXO       OOOOX         OX         X         O
  X XX      XXOOX         O X       OOOO        O
 O         XO X          X X       O          O O
          OXX      OOOO XXX     O          X    O
        OO       XXXO         XOO         XXO   O
     XXO         XOX         O          O       O
      X O          O       XX O         XO      O
   X  O         XOOOXX      X O        X  O     O
        XO        X O          OX         OX    O
           O          OX         OXXX       O   O
  OX         OX XX      O                      OO
OO        OO          OX       XXOX         XX  O
      X X    X  XO X      XOOOO        O        O
XXX         OOX       OOOXX         OX         OO
     XXO        X OX         O          O       O
  X O          O          O         XOXX        O
      O        XXO       X  O         XO        O
    X O        X O        X O         XO        O
  XX        O X         OOX         O X         X
OO        OO       X X          X           X   O
    OOOO X        OXXX       X                  O
   X O         XOX        XO          O         O
  OOOOX       X X          X                    O
    X   O      X   O        XXO          O      O
 OOOO         XXX         X                     O
    X OXX        OX         O          O        O
   XO          OX         OXX        O          O
   X O          O          OX        XOX        O
    XXXOX         O          O          O       O
    O       X  O       X XO         XO          O
 XX        OOX         O X        XOX         OOO
   O         XO        XXO          O X         O
     XO        OOOO        XOX         XXX      O
      XO          OXX        O          OX      O
O         XO         X OXX        OO         XXOO
   OOOOX        OXX        X  X                 O
   XX X        XOOOO      X OX         OOX      O
   OX        XO          O X        O X         O
     X    O       XX O       X  O          O    O
   O          OX         OX X       OX          O
    XO          OXX        O   X      O         O
X        X O          OX         O X        O   O
        X O          OX         OX         O X  O
       OOOOX        XO          OXXX       XOX  O
        XX X       X XOX       OOOO         O   O
      OOOOX         OXX        OOX        XXX   O
 O          O           X       X XO         XO O
 XXO         XOX         O          O           O
X   O       XX OX         O          O          O
    XOX         O  X      XO          O         O
O X        XOX        XOO         X O           O
        XOX         OX        XO          O     O
O        X X        XX O          O          O  O
   OXX       XO X        O          O           O
       O          O          OXX        OXX     O
XO         XO         XX           O          O O
    OOOO       XXO         XX X                 O
      O        XXO         XO X        O        O
     XOO          OX        XXO X         O     O
     X    OX      XX O          O          O    O
         O          O         XO X       XO X   O
        XO          OX        XOX         O     O
         O     X X  O       XX O          O     O
OOO        O         X OX         OXX        XX O
  O          O         XO          XX         XOO
O                   XX O        XXO          O  O
          O X        OXX        O X        O    O
      O        X O          OXXX       O        O
      OOOO        X O          OXX        X XX  O
   XXO         XOOOO       O X        XX        O
   O          OX         OXX        OX          O
         XO          XO          XOX          O O
XOOOO        O          XXX         X     