XXOXX        O          O                      OO
XOXXXOXXXOXXXOOOO  O    O   O                   O
XXXOXXXOXXXOOO O       O   O           O        O
XXOXX        O          O                      OO
XXOXXXOXXXOXOOX         OOO        O O          O
XXOXXXOXXXOXOOXOXO XXXOO O  OO  O     O         O
XXOXX        O          O                      OO
XXOXX        O          O                      OO
XXOXXXOXXXOXXOXOXXOOXOOOOXOOOXXOXX  O    OO  O  O
XOXXXOXXXOXXOOXOOXOXXXOXXOOO  O     OO O        O
